apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stardog.fullname" . }}-password
  namespace: {{ include "stardog.namespace" . }}
  labels:
    helm.sh/chart: {{ include "stardog.chart" . }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
type: Opaque
data:
  password: {{ b64enc .Values.admin.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stardog.fullname" . }}-license
  namespace: {{ include "stardog.namespace" . }}
  labels:
    helm.sh/chart: {{ include "stardog.chart" . }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
type: Opaque
data:
  stardog-license-key.bin: {{ .Values.licenseBase64 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stardog.fullname" . }}-properties
  namespace: {{ include "stardog.namespace" . }}
  labels:
    helm.sh/chart: {{ include "stardog.chart" . }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
data:
  stardog.properties: |
    {{- (.Files.Glob "files/stardog.properties").AsConfig | nindent 4 }}
      pack.enabled={{ .Values.cluster.enabled }}
      pack.zookeeper.address={{ if .Values.zookeeper.enabled }}{{- template "zkservers" . }}{{ else }}{{ .Values.zookeeper.addresses }}{{ end }}
      pack.node.join.retry.count=15
      pack.node.join.retry.delay=1m
{{- if .Values.traffic.encrypt }}
      javax.net.ssl.keyStore=/etc/stardog-keystore/stardog-keystore.pkcs12
      javax.net.ssl.keyStorePassword={{ .Files.Glob "templates/keystore-password.txt" }}
      javax.net.ssl.keyStoreType=PKCS12
{{- end }}
