apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stardog.fullname" . }}-password
  namespace: {{ include "stardog.namespace" . }}
  labels:
    helm.sh/chart: {{ include "stardog.chart" . }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": "hook-failed"
type: Opaque
data:
  password: {{ (coalesce .Values.admin.password (randAlphaNum 8)) | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stardog.fullname" . }}-keystore-password
  namespace: {{ include "stardog.namespace" . }}
  labels:
    helm.sh/chart: {{ include "stardog.chart" . }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": "hook-failed"
type: Opaque
data:
  password: {{ randAlphaNum 8 | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stardog.fullname" . }}-license
  namespace: {{ include "stardog.namespace" . }}
  labels:
    helm.sh/chart: {{ include "stardog.chart" . }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
type: Opaque
data:
  stardog-license-key.bin: {{ .Values.licenseBase64 }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "stardog.fullname" . }}-properties
  namespace: {{ include "stardog.namespace" . }}
  labels:
    helm.sh/chart: {{ include "stardog.chart" . }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
stringData:
  {{- (.Files.Glob "files/stardog.properties").AsConfig | nindent 2 }}
    pack.enabled={{ .Values.cluster.enabled }}
    pack.zookeeper.address={{ if .Values.zookeeper.enabled }}{{- template "zkservers" . }}{{ else }}{{ .Values.zookeeper.addresses }}{{ end }}
    pack.node.join.retry.count=15
    pack.node.join.retry.delay=1m
{{- if .Values.traffic.encrypt }}
    javax.net.ssl.keyStore=/etc/stardog-keystore/stardog-keystore.pkcs12
    javax.net.ssl.keyStorePassword={{ include "stardog.keystorePassword" . }}
    javax.net.ssl.keyStoreType=PKCS12
{{- end }}
