apiVersion: v1
kind: Service
metadata:
  name: {{ include "stardog.fullname" . }}
  namespace: {{ include "stardog.namespace" . }}
  labels:
    app: {{ include "stardog.fullname" . }}
    helm.sh/chart: {{ include "stardog.chart" . }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
{{- if eq .Values.service.type "LoadBalancer" }}
  ports:
  - port: {{ .Values.ports.server }}
    name: server
  {{- if .Values.ports.sql }}
  - port: {{ .Values.ports.sql }}
    name: sql
  {{- end }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
{{- end}}
  selector:
    app: {{ include "stardog.fullname" . }}
